### PR TITLE
Challenge one completed, tests passed

### PR DESCRIPTION
**Pull request by pyrofemme**
no fun comments, sorry, I'll get you next time

### CODE REVIEW

**Comment by pyrofemme** [comment]
I made another commit and it mapped to this pull request. I don't think that was supposed to happen but here we are.

**Comment by zreichert** [comment]
@pyrofemme  You are very close!  Please see https://github.com/pyrofemme/python_practice/pull/1 for a fix to the tests and a hint on how to get the tests passing.

**Comment by zreichert** [comment]
@pyrofemme If you want some help let us know.

**Comment by pyrofemme** [comment]
Please review @cowofevil @zreichert . Checks are still failing.

**Comment by zreichert** [comment]
noice

**Pull request merged**
